### ISSUE TITLE
Add Options for Spindle Delay/Pause

### ISSUE THREAD

**Issue by vincentization** [buildbotics/bbctrl-posts#4]
We sometimes run into issues with the spindle not spinning before engaging the workpiece. I was looking for methods how we can prevent this and found that people are adding dwell times to their gcode/postprocessors. Since we are using Fusion360 for almost all of our CAM, I thought it would be extremely helpful if the post processor supported this directly. Apparently its possible to add these options directly to the dialog in fusion using the postprocessor as I found out over in the Onefinity board:
![image](https://github.com/user-attachments/assets/b1fc5cc8-53d1-42c5-b71f-76651e1c6e5e)

Do you think it would make sense to include this for the buildbotics postprocessors as well? Or is this the wrong place anyway and it should rather be added to the program start script instead? I want to avoid changing the postprocessor manually, since this would risk losing the feature after the next update.

**Comment by DougCoffland** [comment]
I'd prefer to keep the post processor as simple as possible. I think a
better solution would be to put the command in the 'program-start' box or
the 'tool-change' box on the SETTINGS->General page.

You may want to consider a prompt message rather than a simple dwell
command.

The following GCode command will cause a prompt message to be displayed:

M0 (MSG, Click OK when the spindle is up to speed)

Hope this helps,
Doug

**Comment by vincentization** [comment]
Yes I would also prefer the message prompt 👍🏻 But isn't the code in program start executed **before** the actual program that has been selected to run? If thats the case, the message would also appear before any M3 command has even be issued

**Comment by DougCoffland** [comment]
The code in the 'program-start' box is inserted at the beginning of the
gcode program after the program has been selected and loaded. If you use
the M0 prompt, or the dwell command in the 'program-start' box then you
will have to insert the M3 command before the M0 command.

Actually, this may not work very well because you need to know the desired
speed when you start the spindle. If you put it in the 'program-start' box
or the 'tool-change' the spindle speed will always be the same.

I am looking at the F360 post processor to see how difficult it might be to
implement this change. I don't actually have F360, so I'll probably be
asking you to test the new post processor.

Doug

**Comment by vincentization** [comment]
Yeah I thought so too, post processor seems like a more robust and flexible solution.
I just tried adding it to the fusion post processor and it seems to work fine and only required very minor changes 👍🏻 

Attached it as a txt file here since cps files are not supported:
[buildbotics_delay+pause.txt](https://github.com/user-attachments/files/17664401/buildbotics_delay%2Bpause.txt)

I could also submit it as a pull request if you like but the buildbotics post processors in github are outdated

**Comment by DougCoffland** [comment]
That's great. Can you send me a screen shot of the new post processor
properties dialog. I'll check in the update.

Doug

**Comment by vincentization** [comment]
here you go:
![fusion_pp_delay](https://github.com/user-attachments/assets/6bfc259a-2bf4-4d53-9efb-2155a8101507)

not sure about the naming though, have also considered naming it "Spindle Pause"

**Comment by DougCoffland** [comment]
I think the new property names are fine. If you provide me with a short
paragraph on how each of the new properties work, I'll add that text to the
Readme file. Also, if you give me your name, I'll attribute the changes to
you in the Readme file.

Doug

**Comment by vincentization** [comment]
ok sure, I tried to match the phrasing of the existing Readme:
- "Spindle Delay" was added to insert a delay, specified in seconds, after the spindle start command has been issued (M3). This is useful if you experience issues with your spindle not reaching the desired speed quickly enough before engaging with the material.
- "Spindle Confirmation" feature was added to insert a pause with a prompt (M0) after the spindle start command (M3). This lets users manually confirm if the spindle is running correctly before continuing with their program.

btw I just realised I added a comment in the beginning of the postprocessor file I shared. You can ignore that, its meant for the group of people that uses our cnc.

My name is Vincent Schmidt but I came across the idea in a onefinity [pullrequest](https://github.com/OneFinityCNC/onefinity-post-processors/pull/1) from @mikehentges

For the readme I also made a clean screenshot of the latest UI and a little screencap that shows how to add the buildbotics postprocessor from within fusion
![Fusion_post_add](https://github.com/user-attachments/assets/2f4b6c89-cf70-4254-b7af-46746a34ff79)
![Fusion_post_buildbotics](https://github.com/user-attachments/assets/2b36bac8-bf2e-4149-99af-17d4da9d9789)

**Comment by DougCoffland** [comment]
Hi Vincent,

The new post processor is up on github and replaces the previous post
titled 'buildbotics.cps'. I also put your descriptions in the readme file.

Thank you so much for your help.

Thanks,
Doug

**Comment by vincentization** [comment]
thanks a lot Doug, happy to help 👍🏻
I guess we can close this issue now
